servers = ["localhost", "dhcp1.example.com", "10.0.0.1:9001"]
default_port = 4321
# Optional, default: no timeout
timeout_seconds = 3
# Optional, default: available logical core count
thread_count = 512
