[dhcp]
net = "10.0.0.0"
prefix_length = 8
lease_time_seconds = 3600

[server]
listen_cluster = "[::]:1234"
listen_dhcp = "127.0.1.1:4321"

[cluster]
id = 0
heartbeat_timeout_millis = 2000

[[peers]]
id = 1
host = "localhost:1235"

[[peers]]
id = 2
host = "localhost:1236"
