[dhcp]
net = "10.0.0.0"
prefix_length = 8
lease_time_seconds = 3600

[server]
listen_cluster = "[::]:1235"
listen_dhcp = "127.0.1.2:4321"

[cluster]
id = 1
heartbeat_timeout_millis = 2000

[[peers]]
id = 0
host = "localhost:1234"

[[peers]]
id = 2
host = "localhost:1236"
