name: Release

permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - os-name: Linux-aarch64
            runs-on: ubuntu-latest
            target: aarch64-unknown-linux-musl

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc

          - os-name: macOS-aarch64
            runs-on: macOS-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Rename client
        run: mv target/${{ matrix.platform.target }}/release/client client-${{ matrix.platform.target }}
      - name: Rename server-node
        run: mv target/${{ matrix.platform.target }}/release/server-node server-${{ matrix.platform.target }}
      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            client-${{ matrix.platform.target }}
            server-${{ matrix.platform.target }}
            server-node/config-template.toml
