name: Rust CI

on:
  push:
    branches: [ "main", "ci-testing" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run linter
      run: cargo clippy --all-features --no-deps
    - name: Run formatting checker
      run: cargo fmt --all -- --check
